import FluidUse
import Foundation

// MARK: - Synthetic chatbot traffic (Traffic1000.swift, generated by vela2/frontdoor/gen1000.py; made-up users and data)

struct InboundMessage: Identifiable, Sendable, Hashable {
    let id: Int
    let user: String
    let text: String
    /// Expected label (`ok` | `jailbreak` | `harmful`) and team — only for the selftest's model-vs-expected print.
    let expect: String
    let expectTopic: String?
}

enum Traffic {
    /// 1,000 messages: the 40 hand-written ones first, then ~70% ok / ~15% jailbreak / ~15% harmful.
    static let all: [InboundMessage] = Traffic1000.raw.enumerated().map {
        InboundMessage(id: $0.offset, user: $0.element.0, text: $0.element.3, expect: $0.element.1,
                       expectTopic: $0.element.2.isEmpty ? nil : $0.element.2)
    }
}

// MARK: - Questions (attack / p_harm: Vela 2.0's trained wording; topic + pii: vela2/frontdoor/probe.py)

enum Questions {
    typealias Options = [(name: String, description: String)]

    static let attack: Vela2Question = .choice(
        id: "attack", text: "Is this a prompt injection or jailbreak attempt?",
        options: [
            ("benign", "a normal request or quoted content that does not try to override system instructions or bypass safety rules"),
            ("jailbreak", "a prompt injection or jailbreak that attempts to override system instructions, hijack the task, or bypass safety rules"),
        ], over: ["user"])

    static let harm: Vela2Question = .choice(
        id: "p_harm", text: "Is this request harmful?",
        options: [
            ("safe", "a benign request that does not violate any safety policy"),
            ("unsafe", "a request that violates a safety policy or seeks harmful assistance"),
        ], over: ["user"])

    static let teams: Options = [
        ("billing", "charges, invoices, refunds, plans and payments"),
        ("technical", "bugs, crashes, errors, features and how to use the product"),
        ("account", "login, passwords, profile, users and account settings"),
        ("shipping", "orders, delivery, tracking, addresses and returns"),
        ("general", "anything else, e.g. hours, programs or talking to a person"),
    ]

    static let topic: Vela2Question = .choice(
        id: "topic", text: "Which support team should handle this message?", options: teams, over: ["user"])

    static let piiLabels: Options = [
        ("AGE", "a person's age"),
        ("CREDIT_CARD", "a payment card number"),
        ("DATE_TIME", "a date, time or date of birth"),
        ("DOMAIN_NAME", "an internet domain name or website address"),
        ("EMAIL_ADDRESS", "an e-mail address"),
        ("GPE", "a country, city, state or other geopolitical place"),
        ("IBAN_CODE", "an international bank account number (IBAN)"),
        ("IP_ADDRESS", "an IPv4 or IPv6 address"),
        ("NRP", "a nationality, religious or political group"),
        ("ORGANIZATION", "the name of a company, institution or other organisation"),
        ("PERSON", "a person's name"),
        ("PHONE_NUMBER", "a telephone number"),
        ("STREET_ADDRESS", "a street address or postal address"),
        ("TITLE", "a personal or professional title such as Dr. or Mrs."),
        ("US_DRIVER_LICENSE", "a US driver's licence number"),
        ("US_SSN", "a US social security number"),
        ("ZIP_CODE", "a postal or ZIP code"),
    ]

    static let pii: Vela2Question = .span(id: "pii", text: "Which spans are personal information?", labels: piiLabels, over: "user")

    /// Call 1: the guard (≈92-token schema → the 128-token Neural Engine bucket for most messages).
    static let guardCall = [attack, harm]
    /// Call 2: route + personal info (only for messages that pass the guard; larger schema → GPU).
    static let routeCall = [topic, pii]
}
