import FluidAudio
import FluidUse
import Foundation

/// `laya`: answer typed questions about a state with the on-device laya decision model.
///
/// Also carries the parity harnesses used to check the Swift tokenizer and prompt builder
/// against fixtures generated by the Mobius conversion (`make_fixtures.py`).
struct LayaCommand {
    private static let logger = AppLogger(category: "Laya")

    static func run(arguments: [String]) async {
        if arguments.contains("--help") || arguments.contains("-h") {
            printUsage()
            return
        }
        do {
            try await execute(arguments: arguments)
        } catch {
            logger.error("laya failed: \(error.localizedDescription)")
            exit(1)
        }
    }

    // MARK: - Arguments

    private struct Options {
        var modelDirectory: String?
        var lengths: [Int] = [128, 512]
        var state: String?
        var type = "noul"
        var instructions: String?
        var options: [String] = []
        var repeats = 1
        var tokenizerFixtures: String?
        var sequenceFixtures: String?
        var json = false
    }

    private static func parse(_ arguments: [String]) throws -> Options {
        var options = Options()
        var index = 0
        func value(_ flag: String) throws -> String {
            index += 1
            guard index < arguments.count else { throw LayaError.invalidAsset("\(flag) needs a value") }
            return arguments[index]
        }
        while index < arguments.count {
            switch arguments[index] {
            case "--model-dir": options.modelDirectory = try value("--model-dir")
            case "--lengths": options.lengths = try value("--lengths").split(separator: ",").compactMap { Int($0) }
            case "--state": options.state = try value("--state")
            case "--type": options.type = try value("--type")
            case "--instructions": options.instructions = try value("--instructions")
            case "--options":
                options.options = try value("--options").split(separator: "|").map {
                    $0.trimmingCharacters(in: .whitespaces)
                }
            case "--repeats": options.repeats = Int(try value("--repeats")) ?? 1
            case "--tokenizer-fixtures": options.tokenizerFixtures = try value("--tokenizer-fixtures")
            case "--sequence-fixtures": options.sequenceFixtures = try value("--sequence-fixtures")
            case "--json": options.json = true
            default: throw LayaError.invalidAsset("Unknown argument \(arguments[index])")
            }
            index += 1
        }
        return options
    }

    private static func loadManager(_ options: Options) async throws -> LayaManager {
        let configuration = LayaManager.Configuration(lengths: options.lengths)
        let started = Date()
        let manager: LayaManager
        if let directory = options.modelDirectory {
            manager = try await LayaManager.load(from: URL(fileURLWithPath: directory), configuration: configuration)
        } else {
            manager = try await LayaManager.load(configuration: configuration)
        }
        logger.info(
            "Loaded laya buckets \(manager.lengths) in \(String(format: "%.2f", Date().timeIntervalSince(started))) s")
        return manager
    }

    private static func execute(arguments: [String]) async throws {
        let options = try parse(arguments)
        let manager = try await loadManager(options)
        if let path = options.tokenizerFixtures {
            try checkTokenizer(manager: manager, fixtures: path)
        }
        if let path = options.sequenceFixtures {
            try await checkSequences(manager: manager, fixtures: path)
        }
        guard let state = options.state, let instructions = options.instructions else {
            if options.tokenizerFixtures == nil && options.sequenceFixtures == nil {
                printUsage()
            }
            return
        }
        let question = try makeQuestion(type: options.type, instructions: instructions, options: options.options)
        var answer = try await manager.answer(state: state, question: question)
        var timings: [Double] = []
        for _ in 0..<max(1, options.repeats) {
            let started = DispatchTime.now().uptimeNanoseconds
            answer = try await manager.answer(state: state, question: question)
            timings.append(Double(DispatchTime.now().uptimeNanoseconds - started) / 1e6)
        }
        timings.sort()
        var encodeTimings: [Double] = []
        for _ in 0..<max(1, options.repeats) {
            let started = DispatchTime.now().uptimeNanoseconds
            _ = manager.encode(state)
            encodeTimings.append(Double(DispatchTime.now().uptimeNanoseconds - started) / 1e6)
        }
        encodeTimings.sort()
        if options.json {
            let payload: [String: Any] = [
                "type": question.type.rawValue,
                "selected": answer.selectedLabel,
                "probabilities": Dictionary(uniqueKeysWithValues: zip(question.labels, answer.probabilities)),
                "confidence": answer.confidence,
                "action_probability": answer.actionProbability,
                "tokens": answer.tokenCount,
                "bucket": answer.bucketLength,
                "median_ms": timings[timings.count / 2],
                "state_tokenize_median_ms": encodeTimings[encodeTimings.count / 2],
            ]
            let data = try JSONSerialization.data(withJSONObject: payload, options: [.prettyPrinted, .sortedKeys])
            print(String(decoding: data, as: UTF8.self))
            return
        }
        print("Question (\(question.type.rawValue)): \(instructions)")
        for (label, probability) in zip(question.labels, answer.probabilities) {
            let marker = label == answer.selectedLabel ? "▶" : " "
            print(String(format: "  %@ %-40@ %.4f", marker, label, probability))
        }
        if let score = answer.expectedScore { print(String(format: "  expected level: %.3f", score)) }
        if let noul = answer.noul { print(String(format: "  P(true): %.4f", noul)) }
        print(
            String(
                format:
                    "  confidence %.3f · action %.3f · %d tokens on L%d · median %.2f ms over %d calls (state tokenization %.2f ms)",
                answer.confidence, answer.actionProbability, answer.tokenCount, answer.bucketLength,
                timings[timings.count / 2], timings.count, encodeTimings[encodeTimings.count / 2]))
    }

    static func makeQuestion(type: String, instructions: String, options: [String]) throws -> LayaQuestion {
        switch type {
        case "choice":
            return .choice(
                instructions,
                options: options.map { option -> LayaQuestion.Choice in
                    let parts = option.split(separator: "=", maxSplits: 1).map(String.init)
                    return LayaQuestion.Choice(parts[0], description: parts.count > 1 ? parts[1] : nil)
                })
        case "score":
            return .score(instructions, levels: options)
        case "noul":
            return .noul(instructions)
        default:
            throw LayaError.invalidAsset("--type must be choice, score, or noul")
        }
    }

    // MARK: - Fixture parity

    private struct TokenizerCase: Decodable {
        let text: String
        let ids: [Int]
    }

    private static func checkTokenizer(manager: LayaManager, fixtures: String) throws {
        let cases = try JSONDecoder().decode(
            [TokenizerCase].self, from: Data(contentsOf: URL(fileURLWithPath: fixtures)))
        var failures = 0
        for item in cases {
            let ids = manager.encode(item.text)
            if ids != item.ids {
                failures += 1
                print("MISMATCH \(item.text.debugDescription)\n  expected \(item.ids)\n  actual   \(ids)")
            }
        }
        print("tokenizer fixtures: \(cases.count - failures)/\(cases.count) match")
        if failures > 0 { exit(2) }
    }

    private struct SequenceCase: Decodable {
        let name: String
        let question: String
        let length: Int
        let state: String
        let type: String
        let instructions: String
        /// `[label, description-or-null]` pairs in prompt order.
        let options: [[String?]]
        let ids: [Int]
        let markers: [Int]

        enum CodingKeys: String, CodingKey {
            case name = "case"
            case question, length, state, type, instructions, options, ids, markers
        }
    }

    private static func checkSequences(manager: LayaManager, fixtures: String) async throws {
        let cases = try JSONDecoder().decode(
            [SequenceCase].self, from: Data(contentsOf: URL(fileURLWithPath: fixtures)))
        var failures = 0
        for item in cases {
            let question: LayaQuestion
            switch item.type {
            case "choice":
                question = .choice(
                    item.instructions,
                    options: item.options.map {
                        LayaQuestion.Choice($0[0] ?? "", description: $0.count > 1 ? $0[1] : nil)
                    })
            case "score":
                question = .score(item.instructions, levels: item.options.map { $0[0] ?? "" })
            default:
                question = .noul(item.instructions)
            }
            let sequence = try await manager.tokenSequence(state: item.state, question: question, length: item.length)
            if sequence.ids != item.ids || sequence.markers != item.markers {
                failures += 1
                print("MISMATCH \(item.name)/\(item.question) L\(item.length)")
                print("  expected \(item.ids.count) ids, markers \(item.markers)")
                print("  actual   \(sequence.ids.count) ids, markers \(sequence.markers)")
                if let first = zip(sequence.ids, item.ids).enumerated().first(where: { $0.element.0 != $0.element.1 }) {
                    print(
                        "  first difference at \(first.offset): expected \(first.element.1), actual \(first.element.0)")
                }
            }
        }
        print("sequence fixtures: \(cases.count - failures)/\(cases.count) match")
        if failures > 0 { exit(2) }
    }

    private static func printUsage() {
        print(
            """
            Usage: swift run FluidUseLaya answer --state TEXT --type noul|choice|score --instructions TEXT [--options a|b|c]

            Options:
              --model-dir DIR      Local directory with laya_*_L{N}_options32.mlmodelc/.mlpackage + tokenizer.json
              --lengths 128,512    Buckets to load (default 128,512)
              --options a|b|c      Choice labels (label=description allowed) or score levels, lowest first
              --repeats N          Time N extra calls and report the median
              --json               Machine-readable output
              --tokenizer-fixtures FILE   Check the Swift tokenizer against mobius fixtures/tokenizer-cases.json
              --sequence-fixtures FILE    Check prompt building against mobius fixtures/sequence-cases.json
            """)
    }
}
